### ISSUE TITLE
Create a SASS style architecture

### ISSUE THREAD

**Issue by justin-m-morgan** [vincitaylaran/product-feedback-snowpack#8]
With SASS, we can break up our styles into multiple files and then merge them using the "use" rule. 

While Components will have their own module SCSS files, there will be the global and shared styles (for example, variables). I propose at the very least, we have a "reset" file (for setting some project defaults) and a variables file for colours.

**Comment by vincitaylaran** [comment]
Great idea. Files that should affect every component (resets, normalization, globals) should be imported into the `index.ts` file.
